name: pose_style_gallery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Add this

flutter_icons:                      # Add this section
  android: true
  ios: true
  image_path: "assets/icons/dev_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/dev.jpg
    - assets/images/
    - assets/icons/             # Make sure this is included for safety
